# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 22:41
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import manager.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.IntegerField()),
                ('staff_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Departments')),
            ],
            options={
                'managed': True,
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Departments')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Members')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('objectives', models.CharField(max_length=100)),
                ('project_no', models.CharField(max_length=50)),
                ('project_area', models.CharField(blank=True, max_length=100, null=True)),
                ('exepected_results', models.CharField(blank=True, max_length=170, null=True)),
                ('project_details', models.FileField(blank=True, help_text='Upload project details', null=True, upload_to=manager.models.upload_projectdetails)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('project_reports', models.FileField(blank=True, help_text='Upload project reports', null=True, upload_to=manager.models.upload_projectreports)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=21037)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Departments')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Members')),
            ],
            options={
                'verbose_name': 'Project',
                'managed': True,
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Projectship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='Projecttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('objectives', models.CharField(max_length=100)),
                ('task_no', models.CharField(max_length=50, unique=True)),
                ('task_area', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=21037)),
                ('reports', models.FileField(blank=True, help_text='Upload task reports', null=True, upload_to=manager.models.upload_taskreports)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Members')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Projects')),
            ],
            options={
                'verbose_name': 'Task',
                'managed': True,
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Tasktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('formation_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'managed': True,
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Teamship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField(blank=True, max_length=256, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Members')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Projects')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Tasks')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.Teams')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='members',
            field=models.ManyToManyField(blank=True, through='manager.Teamship', to='manager.Members'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='tasktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Tasktype'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='team',
            field=models.ManyToManyField(blank=True, through='manager.Teamship', to='manager.Teams'),
        ),
        migrations.AddField(
            model_name='projectship',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Tasks'),
        ),
        migrations.AddField(
            model_name='projects',
            name='projecttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Projecttype'),
        ),
        migrations.AddField(
            model_name='projects',
            name='task',
            field=models.ManyToManyField(blank=True, through='manager.Projectship', to='manager.Tasks'),
        ),
        migrations.AddField(
            model_name='projects',
            name='team',
            field=models.ManyToManyField(blank=True, through='manager.Teamship', to='manager.Teams'),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.ManyToManyField(blank=True, to='manager.Roles'),
        ),
        migrations.AddField(
            model_name='departments',
            name='member',
            field=models.ManyToManyField(through='manager.Membership', to='manager.Members'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('department', 'member')]),
        ),
    ]
